


POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "name":"huỳnh sdsdd",
    "phone":"253ssvgs332",
    "password":"545"
}


###


POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "phone":"253ssvhhgs332",
    "password":"545"
}


###


POST http://localhost:4000/api/insert



###


GET http://localhost:4000/api/category


# =======================
###


GET http://localhost:4000/api/price

###


GET http://localhost:4000/api/area


# =======================



###


GET http://localhost:4000/api/post/all 
###


GET http://localhost:4000/api/post/new-post?order=createdAt&order=DESC&limit=3


###

GET http://localhost:4000/api/post/all?page=0&limit=3



###

GET http://localhost:4000/api/post/all?categoryCode=CTPT&limit=10&page=1

# ===================
###

GET http://localhost:4000/api/province



###


###

GET http://localhost:4000/api/post/all?limit=10&pageNumber=0&areaNumber[]=90&areaNumber[]=9999



















###

POST http://localhost:4000/api/post/create-post
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMTNjNTA2MDItMDk5Ny00ZWU4LTgyZmYtNDUwY2E3YTUxNDI5IiwibmFtZSI6Imh14buzbmggc2RzZGQiLCJwYXNzd29yZCI6IiQyYSQxMCRGaC92QXFPTk40N0xIR3hHcnFKVjl1bUFlcW91QmFsZzNpRm5Db2E0Wml0czZwVEVaRFF1UyIsInBob25lIjoyNTMsInphbG8iOm51bGwsImZiVXJsIjpudWxsLCJhdmF0YXIiOm51bGwsImNyZWF0ZWRBdCI6IjIwMjMtMDQtMDRUMTQ6MTk6NTQuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjMtMDQtMDRUMTQ6MTk6NTQuMDAwWiJ9LCJpYXQiOjE2ODEwNDA1NTh9.eXcKaGgg3gMKeABDJiGN2Xht7Ak1fjz_CDu4B9WyEF8
Content-Type: application/json

{
"categoryCode":"CTMB",
"title":"Tiêu đề 33",
"priceNumber":0.022222,
"images":"[\"https://res.cloudinary.com/dmcewmxyx/image/upload/v1681040202/phongtro123/wwryepzazsf8yoomghjb.jpg\",\"https://res.cloudinary.com/dmcewmxyx/image/upload/v1681040204/phongtro123/im5aomsxbpglm7pqv7cp.jpg\",\"https://res.cloudinary.com/dmcewmxyx/image/upload/v1681040207/phongtro123/k0jqatvyjpucfkntrkbq.jpg\",\"https://res.cloudinary.com/dmcewmxyx/image/upload/v1681040212/phongtro123/pftljpng1sjpwvea6o1a.jpg\"]",
"address":"Huyện Bù Gia Mập, Tỉnh Bình Phước",
"priceCode":"E1OUDDDDD",
"areaCode":"NRTTTTTTT",
"description":"Nội dung mô tả",
"target":"Nam",
"province":"Tỉnh Bình Phước",
"category":"Cho thuê mặt bằng",
"areaNumber":2334234
}

###

GET http://localhost:4000/api/post/admin-post
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiOWZmZTg5YzQtNjc1OC00MjQxLWE4NjYtYWNlZTRlOTljYTZhIiwibmFtZSI6IsSQ4bqhdCBQaOG6oW0iLCJwYXNzd29yZCI6IiQyYSQxMCRndnhWT2lRNVpwczZGZUtDL00wMkZPd2ZRZm0vTnBWWG5oeGVSRk1qVWhLZUZLSTJ4eERzRyIsInBob25lIjo4MTc0NDI5NDgsInphbG8iOm51bGwsImZiVXJsIjpudWxsLCJhdmF0YXIiOm51bGwsImNyZWF0ZWRBdCI6IjIwMjMtMDQtMTJUMjI6Mjk6NDEuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjMtMDQtMTJUMjI6Mjk6NDEuMDAwWiJ9LCJpYXQiOjE2ODEzNjI4MzN9.H7dlDtQHyWUvTpEC0LTmmN26TsGclKW1ZIOG1Gmo8W0
###

DELETE http://localhost:4000/api/post/delete-post
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiOWZmZTg5YzQtNjc1OC00MjQxLWE4NjYtYWNlZTRlOTljYTZhIiwibmFtZSI6IsSQ4bqhdCBQaOG6oW0iLCJwYXNzd29yZCI6IiQyYSQxMCRndnhWT2lRNVpwczZGZUtDL00wMkZPd2ZRZm0vTnBWWG5oeGVSRk1qVWhLZUZLSTJ4eERzRyIsInBob25lIjo4MTc0NDI5NDgsInphbG8iOm51bGwsImZiVXJsIjpudWxsLCJhdmF0YXIiOm51bGwsImNyZWF0ZWRBdCI6IjIwMjMtMDQtMTJUMjI6Mjk6NDEuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjMtMDQtMTJUMjI6Mjk6NDEuMDAwWiJ9LCJpYXQiOjE2ODEzNjI4MzN9.H7dlDtQHyWUvTpEC0LTmmN26TsGclKW1ZIOG1Gmo8W0
Content-Type: application/json  

{
    "postId":"3c132e00-95ac-4540-8052-33f151ebbbe2"
}
###

PUT http://localhost:4000/api/user/update
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiOWZmZTg5YzQtNjc1OC00MjQxLWE4NjYtYWNlZTRlOTljYTZhIiwibmFtZSI6IsSQ4bqhdCBQaOG6oW0iLCJwYXNzd29yZCI6IiQyYSQxMCRndnhWT2lRNVpwczZGZUtDL00wMkZPd2ZRZm0vTnBWWG5oeGVSRk1qVWhLZUZLSTJ4eERzRyIsInBob25lIjo4MTc0NDI5NDgsInphbG8iOm51bGwsImZiVXJsIjpudWxsLCJhdmF0YXIiOm51bGwsImNyZWF0ZWRBdCI6IjIwMjMtMDQtMTJUMjI6Mjk6NDEuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjMtMDQtMTJUMjI6Mjk6NDEuMDAwWiJ9LCJpYXQiOjE2ODEzNjI4MzN9.H7dlDtQHyWUvTpEC0LTmmN26TsGclKW1ZIOG1Gmo8W0
Content-Type: application/json  

{
"zalo": "sddsd", 
"name": "Đạt Pham",
 "avatar": "sdds"
}


###


###

GET http://localhost:4000/api/user/detail
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiOWZmZTg5YzQtNjc1OC00MjQxLWE4NjYtYWNlZTRlOTljYTZhIiwibmFtZSI6IsSQ4bqhdCBQaOG6oW0iLCJwYXNzd29yZCI6IiQyYSQxMCRndnhWT2lRNVpwczZGZUtDL00wMkZPd2ZRZm0vTnBWWG5oeGVSRk1qVWhLZUZLSTJ4eERzRyIsInBob25lIjo4MTc0NDI5NDgsInphbG8iOm51bGwsImZiVXJsIjpudWxsLCJhdmF0YXIiOm51bGwsImNyZWF0ZWRBdCI6IjIwMjMtMDQtMTJUMjI6Mjk6NDEuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjMtMDQtMTJUMjI6Mjk6NDEuMDAwWiJ9LCJpYXQiOjE2ODEzNjI4MzN9.H7dlDtQHyWUvTpEC0LTmmN26TsGclKW1ZIOG1Gmo8W0



###


GET http://localhost:4000/api/post/detail-post?postId=00cc1a27-d07f-4815-9fa5-ca75b7407e1e
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiOWZmZTg5YzQtNjc1OC00MjQxLWE4NjYtYWNlZTRlOTljYTZhIiwibmFtZSI6IsSQ4bqhdCBQaOG6oW0iLCJwYXNzd29yZCI6IiQyYSQxMCRndnhWT2lRNVpwczZGZUtDL00wMkZPd2ZRZm0vTnBWWG5oeGVSRk1qVWhLZUZLSTJ4eERzRyIsInBob25lIjo4MTc0NDI5NDgsInphbG8iOm51bGwsImZiVXJsIjpudWxsLCJhdmF0YXIiOm51bGwsImNyZWF0ZWRBdCI6IjIwMjMtMDQtMTJUMjI6Mjk6NDEuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjMtMDQtMTJUMjI6Mjk6NDEuMDAwWiJ9LCJpYXQiOjE2ODEzNjI4MzN9.H7dlDtQHyWUvTpEC0LTmmN26TsGclKW1ZIOG1Gmo8W0
